### ISSUE TITLE
Define clear return types for methods in raft_client

### ISSUE THREAD

**Issue by broccolism** [lablup/raftify#113]
### GOAL
Let's specify return types of functions in raft_client.rs file like:
https://github.com/lablup/raftify/blob/914d3fa0f0830436031196c03d657d21d5f1d6ab/binding/python/src/bindings/raft_client.rs#L27-L32

### TODO
I'm totally newbie with python-rust mapping... so need to:
- [ ] Learn pyo3(https://pyo3.rs/v0.20.2/) and pyo3-asyncio(https://github.com/awestlake87/pyo3-asyncio) first
- [ ] Learn raft_client.rs code: `&'a` grammar and attributes like `#[pyclass], #[pymethods], ...`, `into()` function, etc ...
- [ ] Finally write some code
  - [ ] `raftify.pyi`: declare return type for each functions
  - [ ] `raft_client.rs`
    - [ ] Define new struct and implementation
      - **RULES**: Use `Py-` as prefix, make `inner` field in it.
    - [ ] Change return statements by wrapping objects in proper return type.
